# Generated by Django 4.2.1 on 2023-05-16 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postType', models.CharField(choices=[('Ta', 'Танки'), ('He', 'Хилы'), ('DD', 'ДД'), ('Mh', 'Торговцы'), ('Gm', 'Гилдмастеры'), ('Qg', 'Квестгиверы'), ('Bs', 'Кузнецы'), ('Lw', 'Кожевники'), ('Pm', 'Зельевары'), ('Sm', 'Мастера Заклинаний')], default='Tanks', max_length=2)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('header', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=64)),
                ('advertResponse', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mmorpgapp.advert')),
                ('userTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmorpgapp.advert')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmorpgapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(through='mmorpgapp.AdvertCategory', to='mmorpgapp.category'),
        ),
        migrations.AddField(
            model_name='advert',
            name='userWho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
