# Generated by Django 4.2.1 on 2023-05-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmorpgapp', '0002_alter_advert_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='postType',
            field=models.CharField(choices=[('танки', 'Танки'), ('хилы', 'Хилы'), ('дд', 'ДД'), ('торговцы', 'Торговцы'), ('гилдмастеры', 'Гилдмастеры'), ('квестгиверы', 'Квестгиверы'), ('кузнецы', 'Кузнецы'), ('кожевники', 'Кожевники'), ('зельевары', 'Зельевары'), ('Мастера Заклинаний', 'Мастера Заклинаний')], default='танки', max_length=20),
        ),
    ]
